BBPATH .= ":${LAYERDIR}"

BBFILES += "\
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "virtualization-extra-layer"
BBFILE_PATTERN_virtualization-extra-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_virtualization-extra-layer = "9"

LAYERDEPENDS_virtualization-extra-layer += "core openembedded-layer virtualization-layer"

LAYERSERIES_COMPAT_virtualization-extra-layer = "wrynose"

VIRTUALIZATION_EXTRA_LAYERDIR = "${LAYERDIR}"
