BBPATH .= ":${LAYERDIR}"

BBFILES += "\
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "unit-virtualization-layer"
BBFILE_PATTERN_unit-virtualization-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_unit-virtualization-layer = "10"

LAYERDEPENDS_unit-virtualization-layer += "virtualization-layer virtualization-extra-layer unit-users-layer"

LAYERSERIES_COMPAT_unit-virtualization-layer = "wrynose"

UNIT_VIRTUALIZATION_LAYERDIR = "${LAYERDIR}"
