[Daemon]
Theme=darth_vader
ShowDelay=0

# Since EDID read is failing this timeout will definitely happen
# so make it as low as possible without breaking things. Using 0
# results in plymouth erroring out and not showing the splash.
DeviceTimeout=1
