BBPATH .= ":${LAYERDIR}"

BBFILES += "\
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "yocto-extra-layer"
BBFILE_PATTERN_yocto-extra-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_yocto-extra-layer = "6"

LAYERDEPENDS_yocto-extra-layer += "yocto"

LAYERSERIES_COMPAT_yocto-extra-layer = "whinlatter"
